from cerulean_space.util.identifier import Identifier

TEXTURE_DIR = '../img'
DEFAULT_FONT_NAME = "./font/simfang.ttf"
BACKGROUND_SCALE = 0.2
PLAYER_MAX_HEIGHT = 53500
PLAYER_COLLECT_MAX_HEIGHT = 70000
PLAYER_MIN_HEIGHT = 0
PLAYER_COLLECT_MIN_HEIGHT = 55000
GAME_TICK_RATE = 60
COLLECT_MODE_TIME = 160 * GAME_TICK_RATE
MIN_GARBAGE_COUNT_TO_WIN = 700
RENDERING_HEIGHT = 1080
RENDERING_WIDTH = 1920
PLAYER_MAX_X = RENDERING_WIDTH / 2
PLAYER_MIN_X = -RENDERING_WIDTH / 2
