from cerulean_space.util.identifier import Identifier

TEXTURE_DIR = '../img'
DEFAULT_FONT_NAME = "./font/simfang.ttf"
BACKGROUND_SCALE = 0.2
PLAYER_MAX_HEIGHT = 53500
PLAYER_MIN_HEIGHT = 0
RENDERING_HEIGHT = 1000
RENDERING_WIDTH = 1600
PLAYER_MAX_X = RENDERING_WIDTH / 2
PLAYER_MIN_X = -RENDERING_WIDTH / 2
